# -*- coding: utf-8 -*-
"""shadowmap — occultation shadow maps on the Earth.

Modern implementation of the functionality of the Mathematica
``jleGroup`shadowMap``` package (4.1.4, 2013): given a star and a UT
time, draw the hemisphere of the Earth facing the star — the view from
the occulting body — with coastlines, night-side shading (sun more than
a chosen angle below the horizon), and the occultation shadow track:
straight lines in the fundamental plane at the closest-approach offset
``dist`` (Earth radii), position angle ``pa`` (degrees, N through E),
band half-width ``radius`` (occulting-body radius in Earth radii), and
dashed prediction-error lines.  Mercator and equirectangular maps in
view-frame coordinates are also provided.  Function mapping:

    globe                       smGlobe
    substar_point               smGlobe's view point (via ICRS->ITRS)
    subsolar_point / antisolar_point   smSunPosn's role (via get_sun)
    night_polygon               showShadow / newshad
    coastline_outlines          newcont
    shadow_tracks               drawtracks (+ opPrintDiagnostic notes)
    track_ground_paths          (new: the on-Earth ground tracks of the
                                 shadow lines, drawn on cylindrical maps)
    dist_from_impact_parameter  smDist
    offset_prediction           smOffset

Design: superior implementations preferred over porting (maintainer
direction, 2026-07-14).  Concretely:

* **Time and coordinates: astropy.**  Times are ``astropy.time.Time``
  (UTC in, proper UT1/TT handled internally); star positions are
  ``SkyCoord`` (any frame — catalog ICRS is the natural input, unlike
  the original's apparent-of-date strings).  The sub-star point comes
  from transforming the star direction to ITRS (full precession,
  nutation, aberration, Earth rotation — sub-arcsecond class, replacing
  the original's IAU-1982 GMST + apparent-coordinates assumption); the
  sub-solar point from ``astropy.coordinates.get_sun`` (arcsecond
  class, replacing the ~arcminute Duffett-Smith-style theory in
  smSunPosn).  Earth-rotation accuracy is governed by astropy's IERS
  configuration; with no IERS data (offline, or far-future dates)
  astropy degrades gracefully per ``astropy.utils.iers.conf``.

* **Coastlines: Natural Earth.**  The bundled outline database is the
  public-domain Natural Earth 1:110m coastline (134 polylines, 5128
  vertices; naturalearthdata.com, via the nvkelso/natural-earth-vector
  GitHub repository, fetched 2026-07-14), stored as
  ``jlegroup/data/ne_110m_coastline.npz`` — replacing the ~2100-vertex
  hand-digitized database embedded in the Mathematica package.
  Polylines are properly split at the visible-hemisphere limb and at
  the view-frame ±180 deg meridian (the original dropped whole
  polylines instead).

* **Geometry engine: ported and corrected.**  The view rotation,
  orthographic/mercator/equirectangular projections, night-cap
  construction and hemisphere clipping, track-line construction, and
  the smDist/smOffset methods are ported from the Mathematica source
  (validated against reference output generated by running the
  original; see tests/data/shadowmap-mathematica/).  The original's
  night-shadow placement defect is NOT ported: shadowMap 4.1.4 builds
  the antisolar direction with a sign error that misplaces the night
  cap in view longitude whenever both the view latitude and the solar
  declination are nonzero (up to tens of degrees of terminator error in
  unfavorable geometry — established during validation, see the data
  README).  Here the cap is centered on the true antisolar point, and
  the drawn terminator sits at sun altitude ``-horizon_angle`` to
  machine precision of the spherical model.

Model and units
---------------
The Earth is a sphere of unit radius (display model, as in the
original): latitudes are geocentric, the horizon is geometric (no
refraction — fold refraction into ``horizon_angle`` if wanted, ~0.57
deg), and the terminator is computed from the geocentric apparent sun.
Angles at the API are degrees unless a name says otherwise; fundamental
plane distances are in Earth radii; ``b`` in arcsec, body distance in
au, sky velocity in km/s.  Earth's radius and the au come from
``jlegroup.physicalData`` (BODIES["Earth"].radius_km = 6378.14, the
IAU-1976 value the original hardcoded; AU_KM is DE-405, 1.42e-5
relative above the original's rounded 1.496e8 — visible only in
dist_from_impact_parameter and offset_prediction timing).  The
orthographic map is the view from the star: north up, east right.

Provenance
----------
Geometry/track/smDist/smOffset algorithms ported from Mathematica
jleGroup shadowMap 4.1.4 (MIT license, lineage permissions complete
2026-07-11); astropy replaces jleGroup`timeAndCoords` and smSunPosn;
coastline data is Natural Earth (public domain).  No reference
publication exists for this module; validation is against the original
package's computed output where the port is exact (tracks, smDist,
smOffset, compass directions) and at the superseded theories' accuracy
class where astropy replaces them (see tests/test_shadowmap.py).
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from datetime import datetime as _datetime, timedelta as _timedelta
from importlib import resources

import numpy as np

try:
    from astropy import units as u
    from astropy.coordinates import ITRS, Angle, SkyCoord, get_sun
    from astropy.time import Time
except ImportError as exc:  # pragma: no cover - exercised only without the extra
    raise ImportError(
        "jlegroup.shadowmap requires the optional dependency astropy; "
        "install it with:  pip install \"jlegroup[shadowmap]\""
    ) from exc

from . import physicalData

__all__ = [
    "PROJECTIONS",
    "TrackSet",
    "OffsetResult",
    "Site",
    "MapText",
    "map_coordinates",
    "map_window",
    "plot_sites",
    "plot_texts",
    "star_coord",
    "as_time",
    "substar_point",
    "subsolar_point",
    "antisolar_point",
    "view_rotation",
    "view_rotation_inverse",
    "coastlines",
    "coastline_outlines",
    "night_polygon",
    "find_direction",
    "opposite_direction",
    "shadow_tracks",
    "TrackPaths",
    "track_ground_paths",
    "dist_from_impact_parameter",
    "offset_prediction",
    "globe",
]

PROJECTIONS = ("orthographic", "mercator", "equirectangular")


# ---------------------------------------------------------------------------
# Input coercion (SkyCoord / Time)
# ---------------------------------------------------------------------------


def star_coord(ra, dec=None):
    """Coerce flexible star input to a SkyCoord.

    Accepts a ready SkyCoord (any frame, returned unchanged); a single
    string "HH MM SS[.s] ±DD MM SS[.s]" (colon or space separated); or
    separate ``ra``, ``dec`` as sexagesimal strings (RA in hours, Dec in
    degrees, the occultation-community convention), Angles/Quantities,
    or plain floats **in degrees**.  Bare values are taken as ICRS.
    """
    if isinstance(ra, SkyCoord):
        return ra
    if dec is None:
        if not isinstance(ra, str):
            raise TypeError("single-argument star input must be a SkyCoord "
                            "or an 'RA DEC' string")
        return SkyCoord(ra, unit=(u.hourangle, u.deg), frame="icrs")
    if isinstance(ra, str):
        ra = Angle(ra, unit=u.hourangle)
    elif not isinstance(ra, u.Quantity):
        ra = ra * u.deg
    if isinstance(dec, str):
        dec = Angle(dec, unit=u.deg)
    elif not isinstance(dec, u.Quantity):
        dec = dec * u.deg
    return SkyCoord(ra=ra, dec=dec, frame="icrs")


def as_time(time):
    """Coerce flexible time input to an astropy Time (UTC).

    Accepts a ready Time (returned unchanged); a float (MJD, UTC — the
    package's time currency); a datetime; or a string — ISO formats via
    astropy, plus the legacy jleGroup 6-field form
    "YYYY:MM:DD:HH:MM:SS" with separators colon, space, comma, or slash
    (day 0 and overflowing fields roll over, matching the Mathematica
    date-list convention, e.g. "1990,1,0,0,0,0" = 1989-12-31).
    """
    if isinstance(time, Time):
        return time
    if isinstance(time, (int, float)):
        return Time(float(time), format="mjd", scale="utc")
    if isinstance(time, str):
        try:
            return Time(time, scale="utc")
        except ValueError:
            fields = [p for p in re.split(r"[\s:,/]+", time.strip()) if p]
            if len(fields) == 6:
                y, mo = int(float(fields[0])), int(float(fields[1]))
                d, h, mi, s = (float(x) for x in fields[2:])
                dt = _datetime(y, mo, 1) + _timedelta(
                    days=d - 1.0, hours=h, minutes=mi, seconds=s)
                return Time(dt, scale="utc")
            raise ValueError(f"unrecognized time string: {time!r}") from None
    return Time(time, scale="utc")


def _wrap_deg(lon_deg):
    """Wrap a longitude to (-180, 180]."""
    return -((-lon_deg + 180.0) % 360.0 - 180.0)


def _itrs_direction_latlon(coord, time):
    """Geocentric (lat_deg, east_lon_deg) of the ITRS direction of a coord."""
    itrs = coord.transform_to(ITRS(obstime=time))
    sph = itrs.spherical
    return float(sph.lat.to_value(u.deg)), \
        _wrap_deg(float(sph.lon.to_value(u.deg)))


def substar_point(star, time):
    """Sub-star point (lat_deg, east_lon_deg): where the star is at zenith.

    The star direction transformed to the Earth-fixed ITRS frame at the
    given UT — precession, nutation, aberration, and Earth rotation all
    handled by astropy.  This is the center of the orthographic view.
    """
    return _itrs_direction_latlon(star_coord(star), as_time(time))


def subsolar_point(time):
    """Sub-solar point (lat_deg, east_lon_deg) from the apparent sun."""
    t = as_time(time)
    return _itrs_direction_latlon(get_sun(t), t)


def antisolar_point(time):
    """Antisolar point (lat_deg, east_lon_deg): the center of the night."""
    lat, lon = subsolar_point(time)
    return -lat, _wrap_deg(lon + 180.0)


# ---------------------------------------------------------------------------
# View geometry (ported from shadowMap 4.1.4 xcont/ycont, validated exact)
# ---------------------------------------------------------------------------


def view_rotation(lat, lon, view_lat_deg, view_lon_deg):
    """Rotate earth (lat, lon) [radians] into the view frame centered on
    (view_lat_deg, view_lon_deg): returns (lat', lon') with the view
    center at (0, 0); the visible hemisphere is |lon'| < pi/2.
    Accepts scalars or arrays.
    """
    alpha = math.pi / 2.0 - math.radians(view_lat_deg)
    lam0 = math.radians(view_lon_deg)
    sa, ca = math.sin(alpha), math.cos(alpha)
    d = np.asarray(lon) - lam0
    lat = np.asarray(lat)
    latp = np.arcsin(np.clip(sa * np.sin(lat) - ca * np.cos(lat) * np.cos(d),
                             -1.0, 1.0))
    lonp = np.arctan2(np.cos(lat) * np.sin(d),
                      sa * np.cos(lat) * np.cos(d) + ca * np.sin(lat))
    return latp, lonp


def view_rotation_inverse(latp, lonp, view_lat_deg, view_lon_deg):
    """Inverse of view_rotation: view-frame (lat', lon') -> earth (lat, lon)."""
    alpha = math.pi / 2.0 - math.radians(view_lat_deg)
    lam0 = math.radians(view_lon_deg)
    sa, ca = math.sin(alpha), math.cos(alpha)
    latp = np.asarray(latp)
    lonp = np.asarray(lonp)
    vx = np.cos(latp) * np.cos(lonp)
    vy = np.cos(latp) * np.sin(lonp)
    vz = np.sin(latp)
    lat = np.arcsin(np.clip(ca * vx + sa * vz, -1.0, 1.0))
    lon = lam0 + np.arctan2(vy, sa * vx - ca * vz)
    return lat, lon


def _mercator_y(lat):
    """Mercator ordinate y = log tan(lat/2 + pi/4)."""
    return np.log(np.tan(np.asarray(lat) / 2.0 + math.pi / 4.0))


def _check_projection(projection):
    if projection not in PROJECTIONS:
        raise ValueError(
            f"unknown projection {projection!r}; choose from {PROJECTIONS}")


def _project(latp, lonp, projection):
    """View-frame (lat', lon') arrays -> (N, 2) plot coordinates."""
    if projection == "orthographic":
        return np.column_stack([np.cos(latp) * np.sin(lonp), np.sin(latp)])
    if projection == "mercator":
        return np.column_stack([lonp, _mercator_y(latp)])
    return np.column_stack([lonp, latp])


# ---------------------------------------------------------------------------
# Coastlines (Natural Earth 1:110m, public domain)
# ---------------------------------------------------------------------------

_coastlines_cache = None


def coastlines():
    """The bundled coastline database: a list of 134 polylines, each an
    (N, 2) array of (lat, lon) in radians.

    Natural Earth 1:110m "Coastline" (public domain,
    naturalearthdata.com), bundled as
    jlegroup/data/ne_110m_coastline.npz.  Do not mutate the returned
    arrays.
    """
    global _coastlines_cache
    if _coastlines_cache is None:
        ref = resources.files("jlegroup").joinpath(
            "data/ne_110m_coastline.npz")
        with ref.open("rb") as f:
            z = np.load(f)
            latlon = np.radians(z["latlon_deg"].astype(np.float64))
            offsets = z["offsets"]
        _coastlines_cache = [latlon[a:b]
                             for a, b in zip(offsets[:-1], offsets[1:])]
    return _coastlines_cache


def _split_runs(mask):
    """Start/stop index pairs of the True runs of a boolean array."""
    idx = np.nonzero(np.diff(mask.astype(np.int8)))[0] + 1
    bounds = np.concatenate([[0], idx, [len(mask)]])
    return [(int(a), int(b)) for a, b in zip(bounds[:-1], bounds[1:])
            if mask[a]]


def coastline_outlines(view_lat_deg, view_lon_deg, projection="orthographic"):
    """Coastlines in the view frame, projected: a list of (N, 2) arrays.

    Orthographic: polylines are split at the limb and only the runs on
    the visible hemisphere are kept.  Cylindrical projections: polylines
    are split where they cross the view-frame ±180 deg meridian.  (The
    original culled whole polylines in both situations; splitting is
    required for the long Natural Earth arcs.)
    """
    _check_projection(projection)
    out = []
    for pts in coastlines():
        latp, lonp = view_rotation(pts[:, 0], pts[:, 1],
                                   view_lat_deg, view_lon_deg)
        if projection == "orthographic":
            pieces = _split_runs(np.abs(lonp) < math.pi / 2.0)
        else:
            wraps = np.abs(np.diff(lonp)) > math.pi
            cuts = np.concatenate([[0], np.nonzero(wraps)[0] + 1,
                                   [len(lonp)]])
            pieces = list(zip(cuts[:-1], cuts[1:]))
        for a, b in pieces:
            if b - a >= 2:
                out.append(_project(latp[a:b], lonp[a:b], projection))
    return out


# ---------------------------------------------------------------------------
# Night-side shadow
# ---------------------------------------------------------------------------


def _night_cap(horizon_angle_deg, n=203):
    """Boundary of the night cap as (lat, lon) around (0, 0): the circle
    of angular radius (90 - horizon_angle) deg (closed: the last point
    repeats the first)."""
    t = np.arange(n) * (2.0 * math.pi / (n - 1))
    s = math.sin(math.radians(90.0 - horizon_angle_deg))
    lat = np.arcsin(s * np.sin(t))
    lon = np.arcsin(np.clip(s * np.cos(t) / np.cos(lat), -1.0, 1.0))
    return lat, lon


def _clip_to_hemisphere(pts, side):
    """Clip a closed view-frame polygon to |lon'| < pi/2, closing it along
    the limb through the pole on the ``side`` (+1 north / -1 south) of
    the cap center.  Ported from the original clipgeneral (which errored
    on an entirely hidden polygon; this returns empty)."""
    inr = np.abs(pts[:, 1]) < math.pi / 2.0
    if inr.all():
        return pts
    if not inr.any():
        return np.empty((0, 2))
    inr_ext = np.append(inr, inr[0])
    trans = np.nonzero(inr_ext[:-1] != inr_ext[1:])[0]
    p1, p2 = int(trans[0]), int(trans[1])
    edges = []
    for k in (p1, p2):
        lat0 = pts[k, 0]
        lon_sign = math.copysign(1.0, pts[k, 1]) if pts[k, 1] != 0 else 0.0
        arc = np.linspace(lat0, side * math.pi / 2.0, 159)
        edges.append(np.column_stack(
            [arc, np.full(len(arc), math.pi / 2.0 * lon_sign)]))
    if not inr_ext[p1]:
        edges[0] = edges[0][::-1]
    else:
        edges[1] = edges[1][::-1]
    firstone = bool(inr_ext[0])
    nexttolast = bool(inr_ext[-2])
    n = len(pts)
    if firstone and nexttolast:
        return np.vstack([pts[:p1 + 1], edges[0], edges[1], pts[p2:n]])
    if not firstone and not nexttolast:
        return np.vstack([edges[0], pts[p1:p2 + 1], edges[1]])
    if firstone and not nexttolast:
        return np.vstack([pts[:p1 + 1], edges[0], edges[1]])
    return np.vstack([edges[0], pts[p1:p2 + 1], edges[1]])


def night_polygon(view_lat_deg, view_lon_deg, antisolar_lat_deg,
                  antisolar_lon_deg, horizon_angle_deg=0.0,
                  projection="orthographic"):
    """The night-side polygon in projected plot coordinates.

    The region where the sun is more than ``horizon_angle_deg`` below
    the geometric horizon — the spherical cap of angular radius
    (90 - h) deg centered on the antisolar point — rotated into the
    view frame, clipped to the visible hemisphere (orthographic), and
    projected.  Returns an (N, 2) array; empty if no part of the night
    side faces the star.

    The high-level ``globe`` computes the antisolar point with astropy;
    this function is pure spherical geometry (testable in isolation).

    Cylindrical projections return the night region as a single closed
    polygon in CONTINUOUS (unwrapped) view longitude: x may extend
    beyond ±pi, and when the cap encloses a view-frame pole the polygon
    is closed along that pole's map edge (two extra vertices appended
    after the 203 boundary points).  The region tiles with period 2*pi
    in x — draw it at x and x ± 2*pi, as ``globe`` does, and any part
    beyond the map limits clips away.
    """
    _check_projection(projection)
    vf_lat, vf_lon = view_rotation(math.radians(antisolar_lat_deg),
                                   math.radians(antisolar_lon_deg),
                                   view_lat_deg, view_lon_deg)
    vf_lat = float(vf_lat)
    vf_lon = float(vf_lon)
    # Tilt the (0,0)-centered cap so its center lands on the antisolar
    # view-frame position: rotate in latitude by vf_lat, then shift the
    # view-frame longitude by vf_lon.
    alpha = math.pi / 2.0 + vf_lat
    sa, ca = math.sin(alpha), math.cos(alpha)
    lat_c, lon_c = _night_cap(horizon_angle_deg)
    latp = np.arcsin(np.clip(sa * np.sin(lat_c)
                             - ca * np.cos(lat_c) * np.cos(lon_c), -1.0, 1.0))
    lonp = np.arctan2(np.cos(lat_c) * np.sin(lon_c),
                      sa * np.cos(lat_c) * np.cos(lon_c)
                      + ca * np.sin(lat_c)) + vf_lon
    lonp = np.where(np.abs(lonp) > math.pi,
                    lonp - np.sign(lonp) * 2.0 * math.pi, lonp)
    if projection == "orthographic":
        side = math.copysign(1.0, vf_lat) if vf_lat != 0 else 1.0
        clipped = _clip_to_hemisphere(np.column_stack([latp, lonp]), side)
        if len(clipped) == 0:
            return clipped
        return _project(clipped[:, 0], clipped[:, 1], "orthographic")
    # Cylindrical: unwrap the boundary so the polygon is contiguous even
    # when the cap crosses the ±pi view meridian.  The closed boundary
    # comes back to its start (closure ~ 0) unless the cap encloses a
    # view-frame pole (closure ±2*pi) — then close along that pole's map
    # edge (clamped short of the pole on the mercator map, whose y
    # diverges there; the fill clips at the axes limits anyway).
    lonu = np.unwrap(lonp)
    lat_out, lon_out = latp, lonu
    if abs(lonu[-1] - lonu[0]) > math.pi:
        pole_sign = math.copysign(1.0, vf_lat)
        pole_lat = pole_sign * (math.pi / 2.0
                                if projection == "equirectangular"
                                else math.pi / 2.0 - 1e-3)
        lat_out = np.concatenate([latp, [pole_lat, pole_lat]])
        lon_out = np.concatenate([lonu, [lonu[-1], lonu[0]]])
    # representative copy nearest the principal window
    lon_out = lon_out - round(float(np.mean(lon_out))
                              / (2.0 * math.pi)) * 2.0 * math.pi
    return _project(lat_out, lon_out, projection)


# ---------------------------------------------------------------------------
# Sites and text annotations (Labelling feature, new in this package)
# ---------------------------------------------------------------------------


def map_coordinates(lat_deg, lon_deg, view_lat_deg, view_lon_deg,
                    projection="orthographic"):
    """Geographic (lat, lon) [degrees] -> map plot coordinates.

    Returns ``(x, y, visible)``; accepts scalars or arrays (arrays in,
    arrays out).  For the orthographic map ``visible`` is False for
    points on the far hemisphere (which project to mirror positions
    inside the disk — do not draw them); cylindrical projections show
    the whole Earth, so ``visible`` is always True there.

    This is the placement engine for plot_sites/plot_texts and for any
    custom annotation a user wants to draw on a shadow map.
    """
    _check_projection(projection)
    scalar = np.isscalar(lat_deg) and np.isscalar(lon_deg)
    latp, lonp = view_rotation(np.radians(np.asarray(lat_deg, dtype=float)),
                               np.radians(np.asarray(lon_deg, dtype=float)),
                               view_lat_deg, view_lon_deg)
    latp = np.atleast_1d(latp)
    lonp = np.atleast_1d(lonp)
    xy = _project(latp, lonp, projection)
    if projection == "orthographic":
        visible = np.abs(lonp) < math.pi / 2.0
    else:
        visible = np.ones(len(lonp), dtype=bool)
    if scalar:
        return float(xy[0, 0]), float(xy[0, 1]), bool(visible[0])
    return xy[:, 0], xy[:, 1], visible


def map_window(lat_min, lat_max, lon_min, lon_max, view_lat_deg, view_lon_deg,
               projection="orthographic", pad=0.03, n=73):
    """Map-coordinate bounding box (xmin, xmax, ymin, ymax) of a
    geographic lat/lon window — the zoom engine.

    The window's image is curved in map coordinates, so its boundary is
    sampled (``n`` points per edge) and the box padded by ``pad`` (a
    fraction of each span).  ``lon_min > lon_max`` means the window
    crosses the ±180 meridian.  A window containing a view-frame pole is
    rejected on the mercator map (unbounded ordinate) and clamped to the
    map edge on the equirectangular; on the orthographic map, window
    parts on the far hemisphere are ignored (entirely-hidden windows
    are an error).

    Limitation: on cylindrical maps a window straddling the view-frame
    ±180 deg meridian (the anti-sub-star meridian, far from any track)
    is boxed correctly but map content is only drawn on the principal
    side of the seam.
    """
    _check_projection(projection)
    if lat_min >= lat_max:
        raise ValueError("map_window requires lat_min < lat_max")
    lon_span = (lon_max - lon_min) % 360.0
    if lon_span == 0.0:
        raise ValueError("map_window requires a nonzero longitude span")

    lats = np.linspace(lat_min, lat_max, n)
    lons = lon_min + np.linspace(0.0, lon_span, n)
    edge_lat = np.concatenate([np.full(n, lat_min), np.full(n, lat_max),
                               lats, lats])
    edge_lon = np.concatenate([lons, lons,
                               np.full(n, lon_min),
                               np.full(n, lon_min + lon_span)])
    xs, ys, vis = map_coordinates(edge_lat, edge_lon,
                                  view_lat_deg, view_lon_deg, projection)

    # a view-frame pole inside the window bounds the window at the map
    # edge (equirectangular), blows up (mercator), or adds its own
    # image point (orthographic)
    clamp_y = []
    for sign in (1.0, -1.0):
        plat, plon = view_rotation_inverse(sign * math.pi / 2.0, 0.0,
                                           view_lat_deg, view_lon_deg)
        plat, plon = math.degrees(float(plat)), math.degrees(float(plon))
        inside = (lat_min <= plat <= lat_max
                  and (plon - lon_min) % 360.0 <= lon_span)
        if not inside:
            continue
        if projection == "mercator":
            raise ValueError(
                "zoom window contains a view-frame pole: the mercator "
                "ordinate is unbounded there — shrink the window or use "
                "the equirectangular projection")
        if projection == "equirectangular":
            clamp_y.append(sign * math.pi / 2.0)
        else:
            px, py, pvis = map_coordinates(plat, plon, view_lat_deg,
                                           view_lon_deg, projection)
            if pvis:
                xs = np.append(xs, px)
                ys = np.append(ys, py)
                vis = np.append(vis, True)

    xs, ys = xs[vis], ys[vis]
    if len(xs) == 0:
        raise ValueError("zoom window is entirely on the hidden hemisphere")
    if projection != "orthographic":
        # unwrap x about its circular mean so seam-crossing windows box
        # tightly instead of spanning the whole map
        mean = math.atan2(float(np.mean(np.sin(xs))),
                          float(np.mean(np.cos(xs))))
        xs = mean + (xs - mean + math.pi) % (2.0 * math.pi) - math.pi
    xmin, xmax = float(xs.min()), float(xs.max())
    ymin, ymax = float(ys.min()), float(ys.max())
    for y in clamp_y:
        ymin, ymax = min(ymin, y), max(ymax, y)
    dx, dy = pad * (xmax - xmin), pad * (ymax - ymin)
    return xmin - dx, xmax + dx, ymin - dy, ymax + dy


@dataclass(frozen=True)
class Site:
    """A site to mark on the map: a symbol at geographic lat/lon, with an
    optional label.

    lat_deg, lon_deg : geographic position, degrees (east longitude).
    marker : any matplotlib marker ("o" circle, "s" square, "^" triangle,
        "*", "x", "+", ...).
    filled : filled symbol (True) or open outline (False; ignored by
        line markers like "x"/"+").
    size : symbol size in points.
    color : symbol (and label) color.
    label : optional text drawn beside the symbol.
    label_size : label font size, points.
    label_offset : label placement control.  None (the default) leaves
        placement to the automatic declutter pass of plot_sites (falling
        back to 4 pt upper-right when that pass is disabled).  An
        explicit (dx, dy) in points PINS the label there — the declutter
        pass never moves a pinned label, and routes other labels around
        it.  In a crowded field, pin well clear (20-40 pt) and the
        leader line connects the label back to its symbol.
    label_ha, label_va : label anchoring (matplotlib ha/va) for pinned
        placement; the declutter pass chooses its own anchoring.
    leader : draw a thin line connecting a pushed-out label back to its
        symbol.  None (default) = automatic: a leader appears when the
        (pinned or auto-chosen) offset exceeds 12 pt; True/False force
        it on/off.
    """

    lat_deg: float
    lon_deg: float
    marker: str = "o"
    filled: bool = True
    size: float = 6.0
    color: str = "black"
    label: str | None = None
    label_size: float = 8.0
    label_offset: tuple | None = None
    label_ha: str = "left"
    label_va: str = "bottom"
    leader: bool | None = None

    #: offset length (points) beyond which leader=None draws a leader.
    LEADER_AUTO_THRESHOLD = 12.0

    #: fallback placement when declutter is off and no offset is pinned.
    DEFAULT_OFFSET = (4.0, 4.0)

    def wants_leader(self, offset=None):
        """Whether the label gets a leader line, for the offset actually
        used (defaults to the pinned offset / fallback)."""
        if self.leader is not None:
            return self.leader
        off = offset if offset is not None else self.label_offset
        if off is None:
            off = self.DEFAULT_OFFSET
        return math.hypot(*off) > self.LEADER_AUTO_THRESHOLD


@dataclass(frozen=True)
class MapText:
    """Free-standing text placed by geographic lat/lon.

    ha/va anchor the text on its point; rotation is in degrees
    counterclockwise (screen frame).
    """

    lat_deg: float
    lon_deg: float
    text: str
    size: float = 9.0
    color: str = "black"
    ha: str = "center"
    va: str = "center"
    rotation: float = 0.0


#: Candidate label directions for the declutter pass, in preference
#: order (upper-right first, cartographic convention), each with the
#: text anchoring that keeps the label on that side of the symbol.
_LABEL_DIRECTIONS = (
    (0.7071, 0.7071, "left", "bottom"),     # NE
    (-0.7071, 0.7071, "right", "bottom"),   # NW
    (0.7071, -0.7071, "left", "top"),       # SE
    (-0.7071, -0.7071, "right", "top"),     # SW
    (1.0, 0.0, "left", "center"),           # E
    (-1.0, 0.0, "right", "center"),         # W
    (0.0, 1.0, "center", "bottom"),         # N
    (0.0, -1.0, "center", "top"),           # S
)

#: Candidate ring radii, points: a close ring, then two leader rings.
_LABEL_RINGS = (5.0, 24.0, 38.0)

#: Clearance margin between placed rectangles, points.
_LABEL_MARGIN = 1.5


def _text_extent_points(ax, text, fontsize):
    """(width, height) of a text in points, measured with the figure's
    renderer."""
    fig = ax.figure
    try:
        renderer = fig.canvas.get_renderer()
    except AttributeError:              # backend without get_renderer
        fig.canvas.draw()
        renderer = fig.canvas.get_renderer()
    probe = ax.text(0.0, 0.0, text, fontsize=fontsize,
                    transform=ax.transAxes)
    ext = probe.get_window_extent(renderer=renderer)
    probe.remove()
    scale = 72.0 / fig.dpi
    return ext.width * scale, ext.height * scale


def _anchor_rect(px, py, off, w, h, ha, va):
    """Rectangle (x0, y0, x1, y1) of a w x h label anchored at
    (px, py) + off with the given ha/va, all in points."""
    x = px + off[0] - {"left": 0.0, "center": 0.5, "right": 1.0}[ha] * w
    y = py + off[1] - {"bottom": 0.0, "center": 0.5, "top": 1.0}[va] * h
    return (x, y, x + w, y + h)


def _overlap_area(a, b, margin=_LABEL_MARGIN):
    """Overlap area of two rectangles inflated by ``margin`` on each side."""
    w = min(a[2], b[2]) - max(a[0], b[0]) + 2.0 * margin
    h = min(a[3], b[3]) - max(a[1], b[1]) + 2.0 * margin
    return max(0.0, w) * max(0.0, h)


def plot_sites(ax, sites, view_lat_deg, view_lon_deg,
               projection="orthographic", auto_labels=True,
               avoid_texts=None):
    """Draw Site markers (and their labels) on an existing map axes.

    Sites on the hidden hemisphere of an orthographic map are skipped.

    With ``auto_labels=True`` (the default), labels whose Site does not
    pin a ``label_offset`` are placed by a deterministic declutter pass:
    each label tries 8 compass positions on rings of 5/24/38 pt (in
    input order, upper-right preferred) and takes the first spot clear
    of every symbol, every pinned label, every label already placed, and
    every ``avoid_texts`` MapText — falling back to the least-
    overlapping candidate when the field is too crowded.  Leader lines
    appear automatically for placements beyond the 12 pt threshold.
    Pinned labels are never moved (they override the pass — and may
    therefore overprint anything).  Call this after the map (and the
    axes limits) are drawn, so screen geometry is final.

    avoid_texts : iterable of MapText the declutter must route around
        (``globe`` passes its ``texts``); they are obstacles only, drawn
        separately by plot_texts.

    With ``auto_labels=False`` every label uses its pinned offset, or
    the 4 pt upper-right fallback.  Returns the list of sites drawn.
    """
    fig = ax.figure
    scale = 72.0 / fig.dpi
    ax.apply_aspect()   # finalize the data->screen transform before measuring

    visible = []
    for site in sites:
        x, y, vis = map_coordinates(site.lat_deg, site.lon_deg,
                                    view_lat_deg, view_lon_deg, projection)
        if vis:
            visible.append((site, x, y))

    # symbols first; collect their screen anchors and obstacle boxes
    anchors = []
    obstacles = []
    for site, x, y in visible:
        ax.plot([x], [y], linestyle="none", marker=site.marker,
                markersize=site.size,
                markerfacecolor=site.color if site.filled else "none",
                markeredgecolor=site.color, zorder=6)
        px, py = ax.transData.transform((x, y)) * scale
        anchors.append((px, py))
        half = site.size / 2.0 + 1.0
        obstacles.append((px - half, py - half, px + half, py + half))

    # free-standing MapTexts are obstacles for the auto placement
    # (appended after the symbol boxes, so own-symbol indexing holds)
    for note in avoid_texts or ():
        x, y, vis = map_coordinates(note.lat_deg, note.lon_deg,
                                    view_lat_deg, view_lon_deg, projection)
        if not vis:
            continue
        px, py = ax.transData.transform((x, y)) * scale
        w, h = _text_extent_points(ax, note.text, note.size)
        obstacles.append(_anchor_rect(px, py, (0.0, 0.0), w, h,
                                      note.ha, note.va))

    labeled = [(i, site) for i, (site, _, _) in enumerate(visible)
               if site.label]
    extents = {i: _text_extent_points(ax, site.label, site.label_size)
               for i, site in labeled}

    # pinned labels (and every label when auto is off) become obstacles
    placements = {}
    for i, site in labeled:
        if auto_labels and site.label_offset is None:
            continue
        off = site.label_offset if site.label_offset is not None \
            else Site.DEFAULT_OFFSET
        placements[i] = (off, site.label_ha, site.label_va)
        obstacles.append(_anchor_rect(*anchors[i], off, *extents[i],
                                      site.label_ha, site.label_va))

    # declutter the rest: first collision-free candidate, else least bad.
    # A site's own symbol box (obstacles[i]) is not an obstacle to its
    # own label — close placement hugging the marker is the ideal.
    for i, site in labeled:
        if i in placements:
            continue
        best = None
        best_area = math.inf
        for ring in _LABEL_RINGS:
            for ux, uy, ha, va in _LABEL_DIRECTIONS:
                off = (ux * ring, uy * ring)
                rect = _anchor_rect(*anchors[i], off, *extents[i], ha, va)
                area = sum(_overlap_area(rect, o)
                           for j, o in enumerate(obstacles) if j != i)
                if area < best_area:
                    best, best_area = (off, ha, va, rect), area
                if area == 0.0:
                    break
            if best_area == 0.0:
                break
        placements[i] = best[:3]
        obstacles.append(best[3])

    for i, site in labeled:
        off, ha, va = placements[i]
        arrowprops = None
        if site.wants_leader(off):
            # plain thin line, stopped short of the marker edge
            arrowprops = dict(arrowstyle="-", linewidth=0.6,
                              color=site.color, shrinkA=2.0,
                              shrinkB=site.size / 2.0 + 1.5, zorder=6)
        x, y = visible[i][1], visible[i][2]
        ax.annotate(site.label, (x, y), textcoords="offset points",
                    xytext=off, fontsize=site.label_size, color=site.color,
                    ha=ha, va=va, arrowprops=arrowprops, zorder=7)

    return [site for site, _, _ in visible]


def plot_texts(ax, texts, view_lat_deg, view_lon_deg,
               projection="orthographic"):
    """Draw MapText annotations on an existing map axes (hidden-hemisphere
    texts are skipped on the orthographic map).  Returns the texts drawn."""
    drawn = []
    for note in texts:
        x, y, visible = map_coordinates(note.lat_deg, note.lon_deg,
                                        view_lat_deg, view_lon_deg,
                                        projection)
        if not visible:
            continue
        ax.text(x, y, note.text, fontsize=note.size, color=note.color,
                ha=note.ha, va=note.va, rotation=note.rotation, zorder=7)
        drawn.append(note)
    return drawn


# ---------------------------------------------------------------------------
# Shadow tracks (ported from drawtracks) and diagnostics
# ---------------------------------------------------------------------------

#: Compass names, verbatim from the original directionList — including the
#: trailing spaces, which the diagnostic notes rely on.
_DIRECTIONS = ("North ", "North-East ", "East ", "South-East ",
               "South ", "South-West ", "West ", "North-West ")


def find_direction(pa_deg):
    """Compass name of a position angle (the returned string keeps the
    original's trailing space)."""
    return _DIRECTIONS[int(((pa_deg + 22.5) % 360.0) // 45.0)]


def opposite_direction(direction):
    """The opposite compass name."""
    return _DIRECTIONS[(_DIRECTIONS.index(direction) + 4) % 8]


@dataclass(frozen=True)
class TrackSet:
    """Shadow-track lines in the fundamental plane (Earth radii, in the
    orthographic view: north up, east right).

    near, center, far : (2, 2) arrays — the two endpoints of the shadow
        edge nearer Earth center, the shadow center line, and the far
        edge (separated by ``radius`` each).
    error_minus, error_plus : (2, 2) arrays — the dashed prediction-
        error lines at near - pred_error and far + pred_error (equal to
        near/far when pred_error is 0).
    note : diagnostic message ("" when the track crosses cleanly),
        verbatim from the original including its line breaks.
    """

    near: np.ndarray
    center: np.ndarray
    far: np.ndarray
    error_minus: np.ndarray
    error_plus: np.ndarray
    note: str

    def lines(self):
        """The three solid lines, near/center/far."""
        return [self.near, self.center, self.far]


@dataclass(frozen=True)
class TrackPaths:
    """Ground tracks of the shadow lines, as view-frame (lat', lon')
    curves — the fundamental-plane lines of TrackSet lifted onto the
    star-facing hemisphere (inverse orthographic projection).

    Each field is an (n, 2) array [lat', lon' radians] spanning limb to
    limb, or None where that line misses the Earth entirely.  Convert to
    geographic coordinates with ``view_rotation_inverse(path[:, 0],
    path[:, 1], view_lat, view_lon)`` — the ground coordinates of the
    predicted path.  ``note`` matches shadow_tracks.
    """

    near: np.ndarray | None
    center: np.ndarray | None
    far: np.ndarray | None
    error_minus: np.ndarray | None
    error_plus: np.ndarray | None
    note: str

    def lines(self):
        """The three solid-line paths, near/center/far (None entries
        included)."""
        return [self.near, self.center, self.far]


def track_ground_paths(dist=0.0, pa_deg=0.0, radius=0.0, pred_error=0.0,
                       n=181):
    """Ground tracks of the five shadow lines (see shadow_tracks for the
    parameters): each fundamental-plane line at perpendicular offset d
    from Earth center crosses the disk where |d| < 1; the on-disk chord,
    lifted to the star-facing hemisphere, is the locus of surface points
    swept by that shadow edge.  Returns a TrackPaths of view-frame
    (lat', lon') curves (None for lines with |d| >= 1).

    This is what the cylindrical projections of ``globe`` draw — the
    original package drew the raw fundamental-plane lines onto those
    maps in map coordinates, which is not meaningful; ground tracks are.
    """
    theta = math.pi / 2.0 - math.radians(pa_deg)
    ct, st = math.cos(theta), math.sin(theta)
    offsets = {
        "near": dist - radius,
        "center": dist,
        "far": dist + radius,
        "error_minus": dist - radius - pred_error,
        "error_plus": dist + radius + pred_error,
    }
    paths = {}
    for name, off in offsets.items():
        if abs(off) >= 1.0:
            paths[name] = None
            continue
        half = math.sqrt(1.0 - off * off)
        s = np.linspace(-half, half, n)
        x = off * ct - s * st
        y = off * st + s * ct
        latp = np.arcsin(np.clip(y, -1.0, 1.0))
        lonp = np.arcsin(np.clip(x / np.cos(latp), -1.0, 1.0))
        paths[name] = np.column_stack([latp, lonp])
    return TrackPaths(note=shadow_tracks(dist, pa_deg, radius,
                                         pred_error).note, **paths)


def shadow_tracks(dist=0.0, pa_deg=0.0, radius=0.0, pred_error=0.0):
    """Shadow-track geometry (ported from drawtracks; validated exact
    against the original).

    dist : closest-approach distance of the shadow CENTER from Earth
        center, Earth radii (see dist_from_impact_parameter).
    pa_deg : position angle of the occulting body relative to the star,
        deg N through E.
    radius : occulting-body radius, Earth radii.
    pred_error : 1-sigma prediction uncertainty, Earth radii.
    """
    theta = math.pi / 2.0 - math.radians(pa_deg)
    ct, st = math.cos(theta), math.sin(theta)
    subdist = dist - radius
    direc = find_direction(pa_deg)
    note = ""
    if subdist > 1.0:
        note = (" No tracks cross the earth\n "
                + "All three tracks are " + direc + "of the earth")
        xm, ym = subdist * ct, subdist * st
        x1 = xm + 1.3 * math.cos(theta + math.pi / 2.0)
        y1 = ym + 1.3 * math.sin(theta + math.pi / 2.0)
    elif subdist <= 0.0:
        if subdist >= -1.0 and dist <= 1.0 and dist + radius > 1.0:
            note = " One track is " + direc + "of the earth"
        elif subdist >= -1.0 and dist > 1.0:
            note = " Two tracks are " + direc + "of the earth"
        elif subdist < -1.0 and dist < 1.0:
            note = (" The entire earth is in the shadow \n "
                    + "One track is " + direc + "of the earth, \n "
                    + "and one track is " + opposite_direction(direc)
                    + "of the earth")
        elif subdist < -1.0 and dist > 1.0:
            note = (" The entire earth is in the shadow \n "
                    + "No tracks cross the earth \n"
                    + " Two tracks are " + direc + "of the earth, \n "
                    + "and one track is " + opposite_direction(direc)
                    + "of the earth")
        xm, ym = subdist * ct, subdist * st
        x1 = xm + 1.3 * math.cos(math.pi / 2.0 + theta)
        y1 = ym + 1.3 * math.sin(math.pi / 2.0 + theta)
    else:
        if dist <= 1.0 and dist + radius > 1.0:
            note = " One track is " + direc + "of the earth"
        elif dist > 1.0:
            note = " Two tracks are " + direc + "of the earth"
        pdist = subdist
        xm, ym = pdist * ct, pdist * st
        a = math.sqrt(abs((1.0 + pdist) * (1.0 - pdist)))
        augmented = a + 0.3
        alpha = math.atan2(augmented, pdist)
        psi = theta + alpha
        hypot = math.sqrt(augmented * augmented + pdist * pdist)
        x1, y1 = hypot * math.cos(psi), hypot * math.sin(psi)
    x2, y2 = 2.0 * xm - x1, 2.0 * ym - y1
    near = np.array([[x1, y1], [x2, y2]])
    shift = np.array([radius * ct, radius * st])
    err = np.array([pred_error * ct, pred_error * st])
    return TrackSet(near=near,
                    center=near + shift,
                    far=near + 2.0 * shift,
                    error_minus=near - err,
                    error_plus=near + 2.0 * shift + err,
                    note=note)


# ---------------------------------------------------------------------------
# smDist / smOffset
# ---------------------------------------------------------------------------


def dist_from_impact_parameter(b_arcsec, distance_au):
    """Impact parameter (arcsec) and geocentric distance (au) -> shadow
    center offset in Earth radii (smDist).

    Uses physicalData BODIES["Earth"].radius_km and AU_KM (the original
    hardcoded 6378.14 km and the rounded au 1.496e8 km; the au
    difference is 1.42e-5 relative).
    """
    r_km = physicalData.BODIES["Earth"].radius_km
    d_km = distance_au * physicalData.AU_KM
    radius_arcsec = math.atan2(r_km, d_km) * (3600.0 * 180.0 / math.pi)
    return b_arcsec / radius_arcsec


@dataclass(frozen=True)
class OffsetResult:
    """Revised occultation prediction from offset_prediction.

    coord : offset-applied star position (ICRS SkyCoord).
    time : revised closest-approach Time (UT).
    b_arcsec : revised impact parameter.
    pa_deg : revised position angle, deg N through E.
    ra_string, dec_string, date_string : formatted conveniences.
    """

    coord: SkyCoord
    time: Time
    b_arcsec: float
    pa_deg: float

    @property
    def ra_string(self):
        return self.coord.ra.to_string(unit=u.hourangle, sep=" ",
                                       precision=4, pad=True)

    @property
    def dec_string(self):
        return self.coord.dec.to_string(unit=u.deg, sep=" ", precision=4,
                                        pad=True, alwayssign=True)

    @property
    def date_string(self):
        return self.time.utc.iso


def offset_prediction(ra, dec, ra_offset, dec_offset, b_arcsec, pa_deg,
                      time, sky_velocity_kms, distance_au,
                      retrograde=False, add_offset_to_star=False):
    """Revise an occultation prediction for a star-position offset without
    re-running the search (the smOffset method: linear relative motion).

    ra, dec : original star position (see star_coord; strings are RA
        hours / Dec degrees sexagesimal).
    ra_offset, dec_offset : the astrometric offset — sexagesimal strings
        (RA offset in HOURS "HH MM SS.ss", Dec offset in degrees, as in
        the original), Angles/Quantities, or floats in DEGREES.  By
        default the offset is SUBTRACTED from the star (equivalent to
        adding it to the body); add_offset_to_star=True adds it instead.
    b_arcsec, pa_deg, time : original closest-approach impact parameter
        (nonzero), position angle, and UT time (see as_time).
    sky_velocity_kms, distance_au : relative sky-plane speed and
        geocentric distance of the body.
    retrograde : True if the body's apparent motion is retrograde
        (flips the sign of the time correction).

    Approximate by construction (the original documents up to ~0.009"
    in b, 1-2 deg in PA, and seconds in time versus a full re-search).
    """
    star = star_coord(ra, dec)
    t0 = as_time(time)

    def _angle(x, default_unit):
        if isinstance(x, str) or isinstance(x, u.Quantity):
            return Angle(x, unit=default_unit) if isinstance(x, str) \
                else Angle(x)
        return Angle(x, unit=u.deg)

    ra_off = _angle(ra_offset, u.hourangle)
    dec_off = _angle(dec_offset, u.deg)
    sign = -1.0 if add_offset_to_star else 1.0
    s_ra_off = sign * ra_off.to_value(u.rad)
    s_dec_off = sign * dec_off.to_value(u.rad)
    dec_rad = star.dec.to_value(u.rad)
    new_star = SkyCoord(ra=star.ra - sign * ra_off,
                        dec=star.dec - sign * dec_off, frame="icrs")
    pa_rad = math.radians(pa_deg)
    b_rad = b_arcsec * math.pi / (3600.0 * 180.0)
    v1 = np.array([b_rad * math.sin(pa_rad), b_rad * math.cos(pa_rad)])
    v2 = np.array([-s_ra_off * math.cos(dec_rad), -s_dec_off])
    v1mag = math.sqrt(v1 @ v1)
    if v1mag == 0.0:
        raise ValueError("offset_prediction requires a nonzero b_arcsec")
    v2mag = math.sqrt(v2 @ v2)
    if v2mag == 0.0:
        raise ValueError("offset_prediction requires a nonzero offset")
    v3 = (v1 @ v2) * (v1 / v1mag) / v1mag
    v4 = v1 - v3
    b_new = math.sqrt(v4 @ v4) * 180.0 * 3600.0 / math.pi
    cos_theta_b = max(-1.0, min(1.0, (v1 @ v2) / (v1mag * v2mag)))
    d_rad = v2mag * math.sin(math.acos(cos_theta_b))
    d_km = distance_au * physicalData.AU_KM * math.tan(d_rad)
    delta_t_sec = d_km / sky_velocity_kms
    if retrograde:
        delta_t_sec = -delta_t_sec
    signed = -delta_t_sec if ra_off.to_value(u.rad) < 0 else delta_t_sec
    t_new = t0 + signed * u.s
    pa_new = pa_deg + 180.0 if (v1 @ v4) < 0 else pa_deg
    if pa_new > 360.0:
        pa_new -= 360.0
    return OffsetResult(coord=new_star, time=t_new, b_arcsec=b_new,
                        pa_deg=pa_new)


# ---------------------------------------------------------------------------
# The map itself (smGlobe)
# ---------------------------------------------------------------------------


def globe(star, time, projection="orthographic", horizon_angle=0.0,
          shadow_gray=0.8, tracks=False, dist=0.0, pa=0.0, radius=0.0,
          pred_error=0.0, sites=None, texts=None, auto_labels=True,
          zoom_latlon=None, zoom_xy=None,
          print_diagnostic=False, ax=None, plot_label=None):
    """Draw the occultation shadow map (the smGlobe product).

    star : SkyCoord (any frame), "HH MM SS ±DD MM SS" string, or an
        (ra, dec) tuple accepted by star_coord.
    time : UT time accepted by as_time (Time, MJD float, ISO string, or
        the legacy "YYYY:MM:DD:HH:MM:SS" form).
    projection : "orthographic" (the view from the star: north up, east
        right, Earth radius 1), "mercator", or "equirectangular" (both
        in view-frame coordinates, sub-star meridian at x = 0).
    horizon_angle : degrees the sun must be below the geometric horizon
        for a point to be shaded (0 = terminator; 18 = astronomical
        dark; add ~0.57 for refraction if wanted).
    shadow_gray : night-side gray level, 0 black to 1 white.
    tracks, dist, pa, radius, pred_error : draw the shadow-track band
        (see shadow_tracks).  On the orthographic map these are the
        straight fundamental-plane lines; on mercator/equirectangular
        maps the on-Earth ground tracks are drawn instead (see
        track_ground_paths) — lines that miss the Earth have no ground
        track there.
    sites : iterable of Site — symbols (with optional labels) placed by
        geographic lat/lon (see plot_sites; hidden-hemisphere sites are
        skipped on the orthographic map).
    texts : iterable of MapText — free text placed by geographic lat/lon
        (see plot_texts).
    auto_labels : run the declutter pass on site labels that do not pin
        a label_offset (see plot_sites); pinned labels are never moved.
    zoom_latlon : (lat_min, lat_max, lon_min, lon_max) in degrees — zoom
        the map to a geographic window (any projection; see map_window,
        including its view-pole and seam caveats).  lon_min > lon_max
        crosses the ±180 meridian.
    zoom_xy : (xmin, xmax, ymin, ymax) — zoom to raw map coordinates
        (orthographic: Earth radii on the disk; cylindrical: view-frame
        radians / mercator ordinate).  Mutually exclusive with
        zoom_latlon.  Label decluttering runs after zooming, so
        placements adapt to the zoomed scale.
    print_diagnostic : print the track diagnostic note (with
        tracks=True), as in the original.
    ax : matplotlib axes to draw into (a new figure is created if None).
    plot_label : title string.

    Returns the matplotlib Axes.
    """
    import matplotlib.pyplot as plt  # optional at import time, as in EPQ03

    _check_projection(projection)
    if zoom_latlon is not None and zoom_xy is not None:
        raise ValueError("give zoom_latlon or zoom_xy, not both")
    coord = star_coord(*star) if isinstance(star, tuple) else star_coord(star)
    t = as_time(time)
    view_lat, view_lon = substar_point(coord, t)
    anti_lat, anti_lon = antisolar_point(t)

    if ax is None:
        _, ax = plt.subplots(figsize=(6.0, 6.0))

    poly = night_polygon(view_lat, view_lon, anti_lat, anti_lon,
                         horizon_angle, projection)
    if len(poly):
        shifts = (0.0,) if projection == "orthographic" \
            else (-2.0 * math.pi, 0.0, 2.0 * math.pi)
        for s in shifts:   # cylindrical night region tiles mod 2*pi
            ax.fill(poly[:, 0] + s, poly[:, 1],
                    facecolor=(shadow_gray,) * 3, edgecolor="none", zorder=1)
    for line in coastline_outlines(view_lat, view_lon, projection):
        ax.plot(line[:, 0], line[:, 1], color="black", linewidth=0.5,
                zorder=2)

    if projection == "orthographic":
        ax.add_patch(plt.Circle((0.0, 0.0), 1.0, fill=False,
                                edgecolor="black", linewidth=0.6, zorder=3))
        ax.set_xlim(-1.2, 1.2)
        ax.set_ylim(-1.2, 1.2)
        if tracks:
            ts = shadow_tracks(dist, pa, radius, pred_error)
            for seg in ts.lines():
                ax.plot(seg[:, 0], seg[:, 1], color="black", linewidth=0.8,
                        zorder=4)
            for seg in (ts.error_minus, ts.error_plus):
                ax.plot(seg[:, 0], seg[:, 1], color="black", linewidth=0.8,
                        linestyle="--", zorder=4)
            if print_diagnostic and ts.note:
                print(ts.note)
    else:
        if projection == "mercator":
            ax.set_xlim(-math.pi, math.pi)
            ax.set_ylim(-3.0, 3.0)
        else:
            ax.plot([-math.pi, -math.pi, math.pi, math.pi, -math.pi],
                    [-math.pi / 2.0, math.pi / 2.0, math.pi / 2.0,
                     -math.pi / 2.0, -math.pi / 2.0],
                    color="black", linewidth=0.6, zorder=3)
            ax.set_xlim(-math.pi * 1.05, math.pi * 1.05)
            ax.set_ylim(-math.pi / 2.0 * 1.05, math.pi / 2.0 * 1.05)
        if tracks:
            tp = track_ground_paths(dist, pa, radius, pred_error)
            for path in tp.lines():
                if path is not None:
                    xy = _project(path[:, 0], path[:, 1], projection)
                    ax.plot(xy[:, 0], xy[:, 1], color="black",
                            linewidth=0.8, zorder=4)
            for path in (tp.error_minus, tp.error_plus):
                if path is not None:
                    xy = _project(path[:, 0], path[:, 1], projection)
                    ax.plot(xy[:, 0], xy[:, 1], color="black",
                            linewidth=0.8, linestyle="--", zorder=4)
            if print_diagnostic and tp.note:
                print(tp.note)
    if zoom_latlon is not None:
        xmin, xmax, ymin, ymax = map_window(*zoom_latlon, view_lat, view_lon,
                                            projection)
        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
    elif zoom_xy is not None:
        xmin, xmax, ymin, ymax = zoom_xy
        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
    ax.set_aspect("equal")
    # annotations go last, once limits and aspect are final — the
    # declutter pass measures real screen geometry
    if sites:
        plot_sites(ax, sites, view_lat, view_lon, projection,
                   auto_labels=auto_labels, avoid_texts=texts)
    if texts:
        plot_texts(ax, texts, view_lat, view_lon, projection)
    ax.set_axis_off()
    if plot_label is not None:
        ax.set_title(plot_label)
    return ax
